In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 9, 16, 25])
print(arr1 + arr2)
print(arr1 - arr2)
print(np.sqrt(arr2))
print(np.var(arr1))
print(arr1.var())
print(arr1.std())

[ 5 11 19 29]
[ -3  -7 -13 -21]
[2. 3. 4. 5.]
1.25
1.25
1.118033988749895


In [8]:
arr1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2 = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(arr1 + arr2)
print(arr1.T)
print(np.dot(arr1, arr2))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
